add risk management document
Tenderize/docs pull request #6
Opened 2022-08-03 23:37 UTC by kyriediculous

2022-08-04 08:37 UTC, vmaark commented on resources/risk-management.md
> +To track these criteria and give statistical insight into performance we have a come up with a concise set of KPI that prioritises profitability and reliability.
typo: `we have a come up with`

2022-08-04 08:37 UTC, vmaark commented on resources/risk-management.md
> +    3. Does it participate in governance proposals, community discussions, and/ or meetups?
typo: `and/ or` should be `and / or`

2022-08-04 08:39 UTC, vmaark commented on resources/risk-management.md
> +- % fees shared to delegators : Fee commission rate
typo: `delegators : Fee` -> `delegators: Fee`

2022-08-04 08:40 UTC, vmaark commented on resources/risk-management.md
> +- slashing frequency (if applicable): We want node operators that get slashes as frequently as possible, preferably not at all.
rather `We want node operators to get slashes as rarely as possible`, no?

2022-08-04 08:45 UTC, vmaark commented on resources/risk-management.md
> +**If Tenderize Liquidity Pools have insufficient liquidity to exchange tASSET for ASSET, w what alternatives exist for me to redeem my tASSET for the staked asset on a 1:1 exchange rate?**
typo: `w what`

2022-08-04 08:47 UTC, vmaark requested changes
some small typos and an inverted adjective

2022-08-09 08:57 UTC, kyriediculous commented
Thanks @vmaark fixed the typos

2022-08-09 08:59 UTC, vmaark approved these changes
🚀

2022-08-09 10:24 UTC, merged